Issue 1 create an entry - Nick Sturz
nsturz/code-journal pull request #5
Opened 2022-07-20 22:58 UTC by nsturz

2022-07-20 23:46 UTC, TimelikeClosure requested changes

2022-07-20 23:46 UTC, TimelikeClosure commented on js/main.js
> +  });
I'd suggest moving the `window` `'beforunload'` listener out of the form `'submit'` listener.

2022-07-21 00:42 UTC, TimelikeClosure approved these changes

2022-07-21 00:42 UTC, TimelikeClosure commented on js/main.js
> +});
While this doesn't break anything, it'd probably be better if it were lumped into `data.js` with the rest of the `data` saving and loading stuff.

2022-07-21 00:43 UTC, nsturz commented on js/main.js
> +});
done!

2022-07-21 00:54 UTC, merged